# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CZclhblflrIsjc02Zk3K0NUPTqh5Y-hj
"""

# Estudiante: corrige este código y haz un pull request con la versión corregida.

dato = int(input("Ingresa un número: "))
print(dato * 2)